#!/usr/bin/python
import sys 
import redis

r = redis.StrictRedis(host='localhost', port=6379, db=0)
if sys.argv[1] == "crea":
	for x in range(0,12):
		r.rpush("lun","N")
		r.rpush("mar","N")
		r.rpush("mer","N")
		r.rpush("gio","N")
		r.rpush("ven","N")
		r.rpush("sab","N")
		r.rpush("dom","N")
	for x in range(13,47):
		r.rpush("lun","G")
		r.rpush("mar","G")
		r.rpush("mer","G")
		r.rpush("gio","G")
		r.rpush("ven","G")
		r.rpush("sab","G")
		r.rpush("dom","G")

	r.set("G_min",21)
	r.set("G_max",21.5)
	r.set("N_min",21)
	r.set("N_max",21.5)
	r.rpush("rele",0)
	r.rpush("timestamp",0)
	r.rpush("min",0)
	r.rpush("max",0)
	r.rpush("s_blocc",0)
print("lun")
print(r.lrange("lun",0,-1))
print("mar")
print(r.lrange("mar",0,-1))
print("mer")
print(r.lrange("mer",0,-1))
print("gio")
print(r.lrange("gio",0,-1))
print("ven")
print(r.lrange("ven",0,-1))
print("sab")
print(r.lrange("sab",0,-1))
print("dom")
print(r.lrange("dom",0,-1))
print("G_min")
print(r.get("G_min"))
print("G_max")
print(r.get("G_max"))
print("N_min")
print(r.get("N_min"))
print("N_max")
print(r.get("N_max"))
print("rele")
print(r.lrange("rele",0,-1))
print("timestamp")
print(r.lrange("timestamp",0,-1))
print("min")
print(r.lrange("min",0,-1))
print("max")
print(r.lrange("max",0,-1))
print("s_blocc")
print(r.lrange("s_blocc",0,-1))
